# ***Regressão Linear Simples***

In [ ]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
## Criando o df para ser usado na regressão linear simples: 
coluna1=[1,2,3,4,5,6,7,8,9,10]
coluna2=[1,5,7,8,4,8,8,10,7,5]
coluna3=[2,5,8,8,3,10,10,9,8,6]

df1=pd.DataFrame(list(zip(coluna1,coluna2,coluna3)), columns= ['estudante','horas_de_estudo','nota_final'])

In [ ]:
# Visualizando o df criado: 
df1

estudante  horas_de_estudo  nota_final
0          1                1           2
1          2                5           5
2          3                7           8
3          4                8           8
4          5                4           3
5          6                8          10
6          7                8          10
7          8               10           9
8          9                7           8
9         10                5           6

In [ ]:
#  Importando o   numpy:
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
## Transformando a coluna horas_de_estudo para um array, a fim de que possamos trabalhar com a variavel independente. 
horas_estudo = np.array(df1.horas_de_estudo).reshape((-1, 1))
print(horas_estudo)

[[ 1]
 [ 5]
 [ 7]
 [ 8]
 [ 4]
 [ 8]
 [ 8]
 [10]
 [ 7]
 [ 5]]


In [ ]:
## Transformando a coluna nota_final para um array, a fim de que possamos trabalhar com a variavel dependente. 
nota = np.array(df1.nota_final).reshape((-1, 1))
print(nota)

[[ 2]
 [ 5]
 [ 8]
 [ 8]
 [ 3]
 [10]
 [10]
 [ 9]
 [ 8]
 [ 6]]


In [ ]:
# Importando  a biblioteca de regressão linear do sklearn
from sklearn.linear_model import LinearRegression

In [ ]:
# Criando o modelo de regressão linear, fazendo o fit de x e y.

modelo = LinearRegression()

modelo.fit(horas_estudo,nota)

LinearRegression()

In [ ]:
# Avaliando o modelo. Qual seu score, intercept e slope?

score = modelo.score(horas_estudo,nota)
intercept = modelo.intercept_
coef = modelo.coef_

print(score)
print(intercept)
print(coef)

0.8533239147729806
[0.57903494]
[[1.00332779]]


* a função .score() do Scikit-learn ou qualquer outra, nosso principal objetivo é saber quão bem nosso modelo irá generalizar, ou seja, ela serve para sabermos se o nosso modelo será efetivo ao receber um dado que ele nunca viu na vida.


* a função modelo.score(X_train, Y_train) irá verificar o número que seu modelo previu e irá comparar com o valor esperado do conjunto de treino. 

In [ ]:
## Inserção de novos dados de teste:  
nova_horas_estudo = np.array([6,9,12,15,16,4]).reshape((-1, 1))
print(nova_horas_estudo)

[[ 6]
 [ 9]
 [12]
 [15]
 [16]
 [ 4]]


In [ ]:
# Aplicando modelo criado fazendo uma previsão de notas no novo conjunto de dados (novo_x)

previsao_nota = modelo.predict(nova_horas_estudo)
print(previsao_nota)

[[ 6.59900166]
 [ 9.60898502]
 [12.61896839]
 [15.62895175]
 [16.63227953]
 [ 4.59234609]]


In [ ]:
# Notas dos novos alunos.

print(previsao_nota)

[[ 6.59900166]
 [ 9.60898502]
 [12.61896839]
 [15.62895175]
 [16.63227953]
 [ 4.59234609]]


# ***Regressão Linear Multipla***

In [ ]:
coluna4=[0,5,15,25,35,45,55,60]
coluna5=[1,1,2,5,11,15,34,35]
coluna6=[4,5,20,14,32,22,38,43]
df2=pd.DataFrame(list(zip(coluna4,coluna5,coluna6)), columns= ['variavel_independente_1','variavel_independente_2','variavel_dependente'])

In [ ]:
df2

variavel_independente_1  variavel_independente_2  variavel_dependente
0                        0                        1                    4
1                        5                        1                    5
2                       15                        2                   20
3                       25                        5                   14
4                       35                       11                   32
5                       45                       15                   22
6                       55                       34                   38
7                       60                       35                   43

In [ ]:
#import numpy as np
from sklearn.linear_model import LinearRegression

## Dados de treino
a = np.array(df2.variavel_independente_1, df2.variavel_independente_2).reshape((-1, 1))
b = np.array(df2.variavel_dependente).reshape((-1, 1))

In [ ]:
model = LinearRegression().fit(a, b)

print('coefficient of determination:', model.score(a, b))
print('intercept:', model.intercept_)
print('slope:', model.coef_)

coefficient of determination: 0.852834775148352
intercept: [4.37676056]
slope: [[0.59577465]]


In [ ]:
## Dados de teste
novo_x = np.arange(10).reshape((-1, 2))

previsao_y = model.predict(novo_x)
print(previsao_y)

ValueError: ignored